# model
model_path: "meta-llama/Llama-3.2-1B"
# model_path: /root/autodl-tmp/hub/models/Llama-3.2-1B
w_bits: 3
sine_soft_q: False
contain_weight_clip_val: False
cache_dir: null
dsq: False

# data
eval_data_local_path:
max_train_samples: -1
max_eval_samples: -1
model_max_length: 2048

# train
train:
  logging_dir: outputs/llama-1B/3bits/baseline/logs
  do_train: True
  do_eval: False
  fp16: False
  bf16: True
  num_train_epochs: 2
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 1
  evaluation_strategy: "no"
  save_strategy: "steps"
  save_steps: 10000
  report_to: "tensorboard"
  save_total_limit: 1
  learning_rate: !!float 1e-5
  weight_decay: 0.
  warmup_ratio: 0.
  lr_scheduler_type: "cosine"
  logging_steps: 1
  tf32: False
  gradient_checkpointing: False
  # qat: True
  optim: "adamw_torch"
  remove_unused_columns: False
  log_on_each_node: False

